### ISSUE TITLE
vuepress version 1.0.0-alpha.48 breaks plugin

### ISSUE THREAD

**Issue by songololo** [Shigma/vuepress-plugin-mathjax#10]
The latest version of `vuepress@next` breaks `vuepress-plugin-mathjax`, giving the following errors in the console:
```
Uncaught Error: Module build failed (from ./node_modules/postcss-loader/src/index.js):
SyntaxError

(913:9) Unknown word

 [90m 911 | [39m  position[33m:[39m absolute[33m;[39m
 [90m 912 | [39m  font-family[33m:[39m MJXZERO[33m;[39m
[31m[1m>[22m[39m[90m 913 | [39m  white space[33m:[39m nowrap[33m;[39m
 [90m     | [39m        [31m[1m^[22m[39m
 [90m 914 | [39m  height[33m:[39m 1px[33m;[39m
 [90m 915 | [39m  width[33m:[39m 1px[33m;[39m

    at eval (cjs.js?!./node_modules/postcss-loader/src/index.js?!./node_modules/@vuepress/core/.temp/plugins-mathjax.css:1)
    at Object../node_modules/css-loader/dist/cjs.js?!./node_modules/postcss-loader/src/index.js?!./node_modules/@vuepress/core/.temp/plugins-mathjax.css (app.js:1499)
    at __webpack_require__ (app.js:767)
    at fn (app.js:130)
    at eval (plugins-mathjax.css?9492:4)
    at Object../node_modules/@vuepress/core/.temp/plugins-mathjax.css (app.js:1070)
    at __webpack_require__ (app.js:767)
    at fn (app.js:130)
    at eval (enhanceApp.js?0708:1)
    at Module../node_modules/vuepress-plugin-mathjax/src/enhanceApp.js (app.js:1854)
```
and
```
./node_modules/@vuepress/core/.temp/plugins-mathjax.css (./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/postcss-loader/src??ref--7-oneOf-1-2!./node_modules/@vuepress/core/.temp/plugins-mathjax.css)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
SyntaxError

(913:9) Unknown word

  911 |   position: absolute;
  912 |   font-family: MJXZERO;
> 913 |   white space: nowrap;
      |         ^
  914 |   height: 1px;
  915 |   width: 1px;
```

Adding (i.e. forcing downgrade to) `vuepress/core@v1.0.0-alpha.47` fixes the issue.

**Comment by shigma** [comment]
I have just released a new version 1.2.5. Does it work now?

**Comment by songololo** [comment]
Upgraded to the latest version and a similar error occurs:

```
✖ Server
  Compiled with some errors in 21.69s

(undefined) ./node_modules/@vuepress/core/.temp/plugins-mathjax.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
SyntaxError

(913:9) Unknown word

  911 |   position: absolute;
  912 |   font-family: MJXZERO;
> 913 |   white space: nowrap;
      |         ^
  914 |   height: 1px;
  915 |   width: 1px;

    at /.../node_modules/webpack/lib/NormalModule.js:302:20
    at /.../node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /.../node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/.../node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /.../node_modules/postcss-loader/src/index.js:207:9
 @ ./node_modules/vuepress-plugin-mathjax/src/enhanceApp.js 1:0-34
 @ ./node_modules/@vuepress/core/.temp/app-enhancers/3.js
 @ ./node_modules/@vuepress/core/.temp/internal/app-enhancers.js
 @ ./node_modules/@vuepress/core/lib/client/app.js
 @ ./node_modules/@vuepress/core/lib/client/clientEntry.js
 @ multi ./node_modules/@vuepress/core/lib/client/clientEntry.js
(undefined) ./node_modules/@vuepress/core/.temp/plugins-mathjax.css
Module build failed (from ./node_modules/postcss-loader/src/index.js):
SyntaxError

(913:9) Unknown word

  911 |   position: absolute;
  912 |   font-family: MJXZERO;
> 913 |   white space: nowrap;
      |         ^
  914 |   height: 1px;
  915 |   width: 1px;

 @ ./node_modules/vuepress-plugin-mathjax/src/enhanceApp.js 1:0-34
 @ ./node_modules/@vuepress/core/.temp/app-enhancers/3.js
 @ ./node_modules/@vuepress/core/.temp/internal/app-enhancers.js
 @ ./node_modules/@vuepress/core/lib/client/app.js
 @ ./node_modules/@vuepress/core/lib/client/serverEntry.js
 @ multi ./node_modules/@vuepress/core/lib/client/serverEntry.js
Error: Failed to compile with errors.
    at /.../node_modules/@vuepress/core/lib/node/build/index.js:186:16
    at finalCallback (/.../node_modules/webpack/lib/MultiCompiler.js:247:12)
    at /.../node_modules/webpack/lib/MultiCompiler.js:270:6
    at done (/.../node_modules/neo-async/async.js:2931:13)
    at runCompilers (/.../node_modules/webpack/lib/MultiCompiler.js:174:48)
    at /.../node_modules/webpack/lib/MultiCompiler.js:181:7
    at /.../node_modules/webpack/lib/MultiCompiler.js:263:7
    at finalCallback (/.../node_modules/webpack/lib/Compiler.js:220:39)
    at /.../node_modules/webpack/lib/Compiler.js:236:13
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/.../node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:33:1)
    at AsyncSeriesHook.lazyCompileHook (/.../node_modules/tapable/lib/Hook.js:154:20)
    at onCompiled (/.../node_modules/webpack/lib/Compiler.js:234:21)
    at /.../node_modules/webpack/lib/Compiler.js:631:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/.../node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/.../node_modules/tapable/lib/Hook.js:154:20)
    at /.../node_modules/webpack/lib/Compiler.js:628:31
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Process finished with exit code 1
```

**Comment by shigma** [comment]
A related PR: mathjax/mathjax-v3#256
I'm trying to figure out a solution...

**Comment by shigma** [comment]
Version 1.2.8 may solve this issue.

**Comment by songololo** [comment]
@Shigma yes it works now with `v1.2.8`, thank you!
